---
formula:
  # Terminal
  - name: zsh
  - name: zsh-syntax-highlighting
  - name: zsh-autosuggestions
  - name: starship
  - name: homebrew/cask/alacritty
  - name: lazydocker
  - name: neovim
  - name: fzf
  - name: k9s
  - name: htop
  - name: tmux
  - name: gdu
  - name: tako8ki/tap/gobang
    tap: tako8ki/tap
  - name: lazydocker
  - name: idoavrah/homebrew/tftui
    tap: idoavrah/homebrew
  - name: tree-sitter
  - cask: font-hack-nerd-font
  # Cli
  - name: jq
  - name: yq
  - name: ripgrep
  - name: rsync
  - name: wget
  - name: curl
  - name: watch
  - name: xz
  - name: lsd
  - name: bat
  # Containers
  - name: colima
  - name: homebrew/core/docker
  - name: helm
  - name: kind
  - name: kubernetes-cli
  - name: lima
  # Environment
  - name: bash
  - name: zsh
  - name: neofetch
  - name: gh
  - name: git
  # Devops
  - name: pulumi/tap/pulumi
    tap: pulumi/tap
  - name: tfenv
  - name: tofuutils/tap/tofuenv
    tap: tofuutils/tap
  - name: ansible
  - name: fluxcd/tap/flux
    tap: fluxcd/tap
  # SDK
  - name: deno
  - name: nvm
  - name: rustup
  - name: golang
  - name: oven-sh/bun/bun
    tap: oven-sh/bun
  # Security
  - cask: 1password
  # Web
  - cask: firefox
base_repository_path: "$HOME"
git_repositories:
  'rfhold/dev':
    remote_origin: "git@github.com:rfhold/dev.git"
